### ISSUE TITLE
Change the .svg of units with another .svg or a .png o .gif

### ISSUE THREAD

**Issue by ValleyInforge** [itajaja/hb#4]
Hello!

I tried to change the svg of the unit. I tried change just with rename it (for example I changed the svg of the archer with the svg of the Warrior) but nothing change. I also tried with a new .svg downloaded or a .gif but nothing. 

Thanks for all the support!

**Comment by itajaja** [comment]
gif or other images are not currently supported, so only `svg`s work. In order to add additional svg you have to:

1. add your svg file to `src/ui/assets/icons`
2. run `node src/ui/assets/icons/extractPaths.js`
3. change the name for a specific [trait](https://github.com/itajaja/hb/blob/master/src/ui/components/traitGlyph.tsx), [action](https://github.com/itajaja/hb/blob/master/src/ui/components/actionGlyph.tsx) or [unit](https://github.com/itajaja/hb/blob/master/src/ui/components/unitGlyph.tsx) in these files.

For example, say you have a svg called `my-archer.svg`, after executing step 1 and 2, you'll have to change `archer: 'highShot'` to `archer: 'myArcher'` in the [unitGlyph](https://github.com/itajaja/hb/blob/master/src/ui/components/unitGlyph.tsx) file. keep in mind that the only svgs I used come from game-icons.net, so if you are using different svgs, you might have to change the `extractPaths.js` a little bit to accomodate the svgs
